Front tests
skbkontur/db-viewer pull request #22
Opened 2020-08-23 13:31 UTC by fakefeik

2020-09-01 07:10 UTC, gangstatracer requested changes

2020-09-01 13:07 UTC, fakefeik commented on DbViewer.Tests/FrontTests/Pages/BusinessObjectTablePage.cs
> +        // public TooltipContent<ColumnSelector> ColumnSelector { get; set; }
поправил

2020-09-01 13:07 UTC, fakefeik commented on DbViewer.Tests/FrontTests/Pages/Validation.cs
> +                // portal.WaitText(message);
поправил

2020-09-02 07:06 UTC, gangstatracer approved these changes

2020-09-02 07:08 UTC, merged