Semke/update back links
skbkontur/db-viewer pull request #80
Opened 2023-06-24 07:40 UTC by semkedaniil

Заменил все стрелки "назад" на новые согласно фирстилю, также добавил заменил старые иконки на новые.

2023-06-26 07:17 UTC, fakefeik reviewed
посмотрел

2023-06-26 07:17 UTC, fakefeik commented on db-viewer-ui/package.json
> -    "@skbkontur/react-icons": ">=3 <=5",
точно не нужно сюда добавить пир-депенденси? чтобы не оказалось несколько пакетов с иконкми в бандле в какой-то момент

2023-06-26 07:17 UTC, fakefeik commented on db-viewer-ui/src/Components/Accordion/Accordion.tsx
> +import { ArrowShapeTriangleADownIcon } from "@skbkontur/icons/esm/icons/ArrowShapeTriangleADownIcon";
точно нужно из esm явно импортить? кажется, сейчас db-viewer собирается в es5 в конечном итоге

2023-06-26 07:17 UTC, fakefeik commented on db-viewer-ui/src/Components/ObjectTable/ObjectTable.tsx
> +import { UiFilterSortADefaultIcon } from "@skbkontur/icons/esm/icons/UiFilterSortADefaultIcon";
нельзя написать просто
`import { UiFilterSortADefaultIcon, UiFilterSortAHighToLowIcon, UiFilterSortALowToHighIcon } from "@skbkontur/icons";`?

2023-06-26 07:17 UTC, fakefeik commented on db-viewer-ui/src/Components/ObjectTable/ObjectTable.tsx
> +import { UiFilterSortAHighToLowIcon } from "@skbkontur/icons/esm/icons/UiFilterSortAHighToLowIcon";
вроде же рекомендовали использовать конкретные иконки, если не нужно супер умное их поведение? типа `ArrowShapeTriangleALeftIcon16Light` вместо `ArrowShapeTriangleALeftIcon`

2023-06-26 07:17 UTC, fakefeik commented on db-viewer-ui/src/Components/Layouts/CommonLayout.tsx
> -CommonLayout.GreyLineHeader = function GreyLineHeader({
серый блок с заголовком мне все-таки больше нравился) есть прототипы? хочу глянуть

2023-06-26 07:33 UTC, semkedaniil commented on db-viewer-ui/src/Components/ObjectTable/ObjectTable.tsx
> +import { UiFilterSortADefaultIcon } from "@skbkontur/icons/esm/icons/UiFilterSortADefaultIcon";
Была проблема, что, если импортить таким образом, то в бандле окажутся все иконки, поэтому импорчу из esm/icons отдельные иконки.

2023-06-26 07:37 UTC, semkedaniil commented on db-viewer-ui/src/Components/Layouts/CommonLayout.tsx
> -CommonLayout.GreyLineHeader = function GreyLineHeader({
Прототипов нет, но согласно замечаниям проектировщика во время задач про редизайн выпиливался GreyLineHeader в подобных местах, так как он сливался с боковым меню. Вместо серого фона добавляется граница снизу.

2023-06-26 08:09 UTC, fakefeik commented on db-viewer-ui/src/Components/ObjectTable/ObjectTable.tsx
> +import { UiFilterSortADefaultIcon } from "@skbkontur/icons/esm/icons/UiFilterSortADefaultIcon";
tree-shaking разве не сработает в конечном итоге?

2023-06-26 09:39 UTC, semkedaniil commented on db-viewer-ui/src/Components/ObjectTable/ObjectTable.tsx
> +import { UiFilterSortAHighToLowIcon } from "@skbkontur/icons/esm/icons/UiFilterSortAHighToLowIcon";
Поправил

2023-06-26 09:40 UTC, semkedaniil commented on db-viewer-ui/package.json
> -    "@skbkontur/react-icons": ">=3 <=5",
Верно, забыл добавить

2023-06-26 10:05 UTC, fakefeik commented on db-viewer-ui/package.json
> -    "@skbkontur/react-icons": ">=3 <=5",
может, сделать однообразно как с остальными? `">=1 <2"`

и можно еще react и react-router поднять `">=16 <=18"`

2023-06-26 12:42 UTC, semkedaniil commented on db-viewer-ui/package.json
> -    "@skbkontur/react-icons": ">=3 <=5",
Сделал однообразно

2023-06-26 12:47 UTC, semkedaniil commented
Не вливай, пожалуйста, в мастер после апрува, я еще в тестирование отдам с пререлизными версиями

2023-06-26 12:52 UTC, fakefeik approved these changes

2023-07-31 11:45 UTC, semkedaniil commented on db-viewer-ui/src/Components/ObjectTable/ObjectTable.tsx
> +import { UiFilterSortADefaultIcon } from "@skbkontur/icons/esm/icons/UiFilterSortADefaultIcon";
Все-таки вернул обратно. Поискал по чату инфры фронтсаппорта, и они говорили, что проблема с tree-shaking [решена в этом пакете](https://kontur.slack.com/archives/C013HTCE18Q/p1660040355188759?thread_ts=1660031686.662779&cid=C013HTCE18Q), но сейчас заметил, что с каких-то версияй эта проблема [проявилась](https://kontur.slack.com/archives/C013HTCE18Q/p1689150912279319).

2023-08-01 08:27 UTC, fakefeik requested changes

2023-08-01 08:27 UTC, fakefeik commented on DbViewer.Cql/DbViewer.Cql.csproj
> +    <TargetFramework>net6.0</TargetFramework>
тут не нужны изменения

2023-08-01 08:27 UTC, fakefeik commented on DbViewer.EntityFramework/DbViewer.EntityFramework.csproj
> +    <TargetFramework>net6.0</TargetFramework>
можем мы тут оставить нетстандарт и старую версию ef? вроде должно работать

2023-08-01 09:40 UTC, semkedaniil commented on DbViewer.TestApi/DbViewer.TestApi.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.5" />
Проблемы с билдом были, одна из библиотек просила версию 7.0.9, можно ее установить

2023-08-02 11:21 UTC, fakefeik approved these changes

2023-08-16 10:54 UTC, semkedaniil commented
@fakefeik , можешь еще раз чекнуть, пожалуйста. Добавил адаптивности в верстку хедера с его элементами и обновил еще пару библиотек

2023-08-16 11:04 UTC, fakefeik approved these changes
вроде норм, а почему потребовалось обновлять selenoid?

2023-08-16 11:07 UTC, semkedaniil commented
Браузерные тесты не поднимались ни локально, ни в джобах. Вот [ишью](https://github.com/aerokube/selenoid/issues/1326).
Валились такие ошибки: `Newtonsoft.Json.JsonReaderException : Unexpected character encountered while parsing value: Y. Path '', line 0, position 0.`

2023-08-16 11:21 UTC, merged